apiVersion: v1
data:
  config.yaml: |
    domain: default-ratelimit
    descriptors:
      - key: PATH
        value: "/status"
        rate_limit:
          unit: minute
          requests_per_unit: 1
      - key: PATH
        rate_limit:
          unit: minute
          requests_per_unit: 1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: istio-system
