apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: "nginx-vm"
  namespace: istio-demo
spec:
  metadata:
    labels:
      app: "nginx-vm"
  template:
    serviceAccount: vm
    network: ""
