apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: "nginx"
  namespace: istio-demo
spec:
  metadata:
    labels:
      app: "nginx"
  template:
    serviceAccount: vm
    network: ""
  probe:
    httpGet:
      port: 80